import { useState } from 'react';
import { format } from 'date-fns';
import { Copy, CalendarIcon, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { cn } from '@/lib/utils';
import { supabase } from '@/integrations/supabase/client';
import { useQueryClient } from '@tanstack/react-query';
import { toast } from '@/hooks/use-toast';
import { useDrivers, useVehicles } from '@/hooks/useDrivers';
import type { Route } from '@/hooks/useRoutes';

interface DuplicateRouteDialogProps {
  route: Route & { route_stops?: Array<Record<string, unknown>> };
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function DuplicateRouteDialog({ route, open, onOpenChange }: DuplicateRouteDialogProps) {
  const queryClient = useQueryClient();
  const { data: drivers } = useDrivers();
  const { data: vehicles } = useVehicles();

  const [name, setName] = useState(`${route.name} — copia`);
  const [date, setDate] = useState<Date>(new Date());
  const [driverId, setDriverId] = useState<string>(route.driver_id ?? 'none');
  const [vehicleId, setVehicleId] = useState<string>(route.vehicle_id ?? 'none');
  const [loading, setLoading] = useState(false);

  const handleDuplicate = async () => {
    setLoading(true);
    try {
      // 1. Create new route
      const { data: newRoute, error: routeErr } = await supabase
        .from('routes')
        .insert({
          name: name.trim(),
          date: format(date, 'yyyy-MM-dd'),
          company_id: route.company_id,
          status: 'draft',
          driver_id: driverId === 'none' ? null : driverId,
          vehicle_id: vehicleId === 'none' ? null : vehicleId,
        })
        .select()
        .single();

      if (routeErr) throw routeErr;

      // 2. Fetch stops of original route
      const { data: originalStops, error: stopsErr } = await supabase
        .from('route_stops')
        .select('seq, address_text, lat, lng, planned_window_start, planned_window_end, notes, recipient_name, recipient_phone')
        .eq('route_id', route.id);

      if (stopsErr) throw stopsErr;

      if (originalStops && originalStops.length > 0) {
        const newStops = originalStops.map(s => ({
          ...s,
          route_id: newRoute.id,
          status: 'pending' as const,
          // tracking_token is auto-generated by DB default (gen_random_uuid())
        }));

        const { error: insertErr } = await supabase.from('route_stops').insert(newStops);
        if (insertErr) throw insertErr;
      }

      queryClient.invalidateQueries({ queryKey: ['routes'] });
      toast({ title: 'Ruta duplicada', description: `"${name}" creada con ${originalStops?.length ?? 0} paradas.` });
      onOpenChange(false);
    } catch (err) {
      toast({ title: 'Error al duplicar', description: err instanceof Error ? err.message : 'Error desconocido', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Copy className="h-5 w-5" />
            Duplicar ruta
          </DialogTitle>
          <DialogDescription>
            Se creará una nueva ruta en borrador con todas las paradas de "{route.name}".
          </DialogDescription>
        </DialogHeader>

        <div className="grid gap-4 py-2">
          <div className="space-y-1.5">
            <Label>Nombre de la nueva ruta</Label>
            <Input value={name} onChange={e => setName(e.target.value)} />
          </div>

          <div className="space-y-1.5">
            <Label>Fecha</Label>
            <Popover>
              <PopoverTrigger asChild>
                <Button variant="outline" className="w-full justify-start text-left font-normal">
                  <CalendarIcon className="mr-2 h-4 w-4" />
                  {format(date, 'dd/MM/yyyy')}
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-auto p-0" align="start">
                <Calendar
                  mode="single"
                  selected={date}
                  onSelect={d => d && setDate(d)}
                  initialFocus
                  className={cn('p-3 pointer-events-auto')}
                />
              </PopoverContent>
            </Popover>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1.5">
              <Label>Conductor</Label>
              <Select value={driverId} onValueChange={setDriverId}>
                <SelectTrigger>
                  <SelectValue placeholder="Sin asignar" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="none">Sin asignar</SelectItem>
                  {drivers?.map(d => (
                    <SelectItem key={d.id} value={d.id}>{d.full_name || 'Sin nombre'}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-1.5">
              <Label>Vehículo</Label>
              <Select value={vehicleId} onValueChange={setVehicleId}>
                <SelectTrigger>
                  <SelectValue placeholder="Sin asignar" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="none">Sin asignar</SelectItem>
                  {vehicles?.map(v => (
                    <SelectItem key={v.id} value={v.id}>{v.plate}{v.label ? ` — ${v.label}` : ''}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button>
          <Button onClick={handleDuplicate} disabled={loading || !name.trim()}>
            {loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Copy className="mr-2 h-4 w-4" />}
            Duplicar
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
